name: "[remoodle/arem] Publish Docker image"

on:
  push:
    branches: [main]
    paths:
      - "remoodle/arem/**"
    tags:
      - "remoodle/arem-*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to ghcr
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE_ID=ghcr.io/remoodle/arem
          GITHUB_REF="${{ github.ref }}"
          IMAGE_TAG=${GITHUB_REF#"refs/tags/remoodle/arem-v"}

          IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/[\/-]/_/g')

          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
          VERSION_TAG="${IMAGE_TAG}.${SHORT_SHA}"

          echo IMAGE_ID=$IMAGE_ID
          echo GITHUB_REF=$GITHUB_REF
          echo IMAGE_TAG=$IMAGE_TAG

          cd remoodle/arem

          docker pull $IMAGE_ID:latest
          docker build . --file Dockerfile --tag $IMAGE_ID:$IMAGE_TAG --cache-from $IMAGE_ID:latest --build-arg VERSION_TAG=$VERSION_TAG
          docker build . --file Dockerfile --tag $IMAGE_ID:latest --cache-from $IMAGE_ID:$IMAGE_TAG --build-arg VERSION_TAG=$VERSION_TAG

          docker push $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:latest
